---
- name: Install dependencies
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
  tags:
    - nodejs
    - dependencies
    
- name: Add Node.js apt key
  ansible.builtin.apt_key:
    url:  https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg    
  tags:
    - nodejs

# https://github.com/nodesource/distributions/blob/master/README.md#debinstall
- name: Add Node.js repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_distribution_release | lower }} main"
    state: present
    filename: nodesource    
  tags:
    - nodejs

- name: Install Node.js
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name: nodejs
  tags:
    - nodejs
